title: Yanjie Zhang
logo: /assets/img/zyj.jpg
description: Master Student of Urban Mobility Institute, Tongji University
url: "https://yanjie99.github.io"
baseurl: "/resume"
#show_downloads: true
theme: jekyll-theme-minimal

author:
  name: "Yanjie Zhang"
  email: "2131371@tongji.edu.cn"
  twitter: "johndoe"
  github: "yanjie99"
  linkedin: "john-doe"
  address: "1239 Siping Rd, Shanghai, CHN"
