title: Yanjie Zhang
logo: /assets/img/headshot_circle.png
description: Master Student of Urban Mobility Institute, Tongji University
email: 2131371@tongji.edu.cn
#show_downloads: true
theme: jekyll-theme-minimal
