title: Yanjie Zhang
logo: /assets/img/zyj.jpg
description: Master Student of Urban Mobility Institute, Tongji University
show_downloads: "true"
theme: jekyll-theme-minimal

# Personal Information
author:
  name: Yanjie Zhang
  email1: yj2021@tongji.edu.cn
  email2: yj2yx@outlook.com
  github: yanjie99
  orcid: 0009-0002-3627-1104
  youtube: UC24X9atI5X7HcUABcMccJ-Q

# Social Links
social:
  email1: yj2021@tongji.edu.cn
  email2: yj2yx@outlook.com
  github: https://github.com/yanjie99
  orcid: https://orcid.org/0009-0002-3627-1104
  youtube: https://www.youtube.com/channel/UC24X9atI5X7HcUABcMccJ-Q  # 替换为你的 YouTube 频道 ID

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Custom Variables
custom_variable: My custom value
